### ISSUE TITLE
SelectCommand - C.1.1.2 - Step 6.2 - Reselect applet

### ISSUE THREAD

**Issue by makinako** [makinako/OpenFIPS201#1]
The requirement is described in SP800-73-4 Part 2 - 3.1.1 - SELECT Card Command:

>If the currently selected application is the PIV Card Application when the SELECT command is given and the AID in the data field of the SELECT command is either the AID of the PIV Card Application or the right-truncated version thereof, then the PIV Card Application shall continue to be the currently selected card application and the setting of all security status indicators in the PIV Card Application shall be unchanged.

At present, there doesn't seem to be an obvious way to achieve this in v2.2.2 of the JCRE without some sort of native/proprietary extension, as an identical sequence of events is fired if an applet is reselected, or deselected then selected again. This is being reviewed but at present this requirement isn't met.

A more detailed analysis of this issue has been documented internally, but may be distributed if needed. To request this information, contact us on piv@makina.com.au.

**Comment by dengert** [comment]
As noted in the the https://github.com/OpenSC/OpenSC/pull/1256 the select AID is a critical issue with OpenSC. OpenSC will attempt to determine if a card can support one or more applets be doing a SELECT AID. It the PIV card does not ignore these unknown AIDs, and leave its state unchanged,  the PIV state may be lost. Users may want to use the same card from multiple long running applications, and the security state should not be reset by attempts to query the card by a SELECT AID for an unknown AID.

**Comment by makinako** [comment]
The problem isn't unknown AID's, it's reselection of the PIV applet. The PIV rules basically can be summarised as follows:
1. **Selection** - If the PIV applet is not selected and becomes selected, the security
conditions must be reset.
2.  **Deselection** - If the PIV applet is selected and becomes not selected (i.e. a different applet
is selected), then the PIV applet becomes selected again, the security
conditions must be reset.
3. **Reselection** - If the PIV applet is selected and a select command is issued again for the
PIV applet (i.e. it is re-selected), then the security conditions must not be
reset.
4. **Invalid Selection** - If the PIV applet is selected and a select command is issued for a nonexistent
applet, then the PIV applet should remain selected and the security
conditions must not be reset.

OpenFIPS201 fails only on point 3 and this is because JCRE's before Javacard 3.0.4 don't have the Applet.reselectingApplet() method, which is described as:
> reSelectingApplet(): This method is used by the applet's process() method or the select() method or applet's deselect() method to determine if it itself is being re-selected on this logical channel.

This has been confirmed with NIST and they are considering options for this, but in the meantime the simple answer is that Javacard implementations prior to 3.0.4 can't pass this test in the PIV Test Runner without some sort of non-standard mechanism provided by the card vendor.

The original goal for OpenFIPS201 was to cast the net as wide as possible and provide support for the many existing Javacard 2.2 ecosystems out there, so if we can't pass accreditation without it then we will have to consider dropping support for older JCRE's...

It would be extremely useful to hear from anyone (even theoretically) considering using OpenFIPS201 on a 2.2.2 platform!

**Comment by martinpaljak** [comment]
I would need to dig deeper into specs, but why can't 2.2.2 satisfy point 3? Looking at code - why don't you use Applet.select() as well?

**Comment by makinako** [comment]
Hi Martin, I have tried using select() but there doesn't appear to be a way to differentiate whether it is called because of an initial select or a reselect. The 3.0.4 Applet.reselectingApplet() method seems to have been included for exactly this reason.

**Comment by darconeous** [comment]
What about using [`deselect()`](https://www.win.tue.nl/pinpasjc/docs/apis/jc222/javacard/framework/Applet.html#deselect())? Is it always called upon re-selection? If not, then that seems like it would do the trick (although the exact behavior might be JCRE implementation dependent)

If it is called even for re-selection, perhaps [`APDU.getCurrentAPDU()`](https://www.win.tue.nl/pinpasjc/docs/apis/jc222/javacard/framework/APDU.html#getCurrentAPDU()) could be used to introspect into into selection APDU and determine if it is a reselect? Even if this is possible I doubt it could be written to work in all cases—but it might at least work for the most common cases.

**Comment by makinako** [comment]
Closing this required migration to JC3.0.4, which has been on the card for a while. This is now completed. As mentioned on the front page, the legacy OpenFIPS201 applet can now be found [here](https://github.com/makinako/OpenFIPS201-jc22).
I've confirmed that there is no way to fix this issue, or fully comply with the mandatory requirements of SP800-73-4 with JC2.2.2.
