### ISSUE TITLE
TLV length check bug

### ISSUE THREAD

**Issue by makinako** [makinako/OpenFIPS201#10]
When using the 'Change Reference Data Admin' command to set key part values, it checks if the 'SEQUENCE' element (0x30) is present but then doesn't check that the length of the sequence corresponds to the remaining length of the apdu.

**Comment by kuhy** [comment]
If I am not mistaken, the same issue also applies to the `putDataAdmin` method. This method does not check the length of the `COMMAND` tag.

**Comment by makinako** [comment]
Yep thanks this is correct! This will be wrapped in the changes coming in the next week or so.
