### ISSUE TITLE
Unable to write data object Biometric Information Templates Group Template

### ISSUE THREAD

**Issue by makinako** [makinako/OpenFIPS201#11]
The APDu fails when writing to the above data object, even though the object was successfully has been created during pre-personalisation. 
It is probably no coincidence that this is the only data object with a 2-byte object identifer (7F61h).
The underlying cause has not yet been found.

**Comment by kuhy** [comment]
Hi! I am not a java card expert, but I think I found a bug related to this issue.

The problem is in the following code snippet:
``` java
else if (buffer[offset] == CONST_TAG_BIOMETRIC_1) {
            if ((short)(buffer[offset] + 1) != CONST_TAG_BIOMETRIC_2) ISOException.throwIt(SW_REFERENCE_NOT_FOUND);
            id = CONST_TAG_BIOMETRIC_2;
            // We don't move the buffer for this special object to include the special data object tag
}
```
I believe `buffer[offset] + 1` should be `buffer[offset + 1]` or something like that.

**Comment by makinako** [comment]
Hi Kuhy,
Your patch fixes one aspect of the bug, however it doesn't correct the reading of the Biometrics template. I'll modify this and close shortly.
