### ISSUE TITLE
Inject Symmetric Key wrong APDU?

### ISSUE THREAD

**Issue by CueMaxX** [makinako/OpenFIPS201#12]
Hello,

under the wiki-page [Security-Personalisation](https://github.com/makinako/OpenFIPS201/wiki/Security-Personalisation) it says I have to inject a symmetric key with the APDU
`0024039B2230208018101112131415161718191A1B1C1D1E1F2021222324252627`
However, when sending that APDU, it returns:

> Exception in thread "main" java.lang.IllegalArgumentException: Invalid APDU: length=33, b1=34
        at apdu4j.CommandAPDU.parse(CommandAPDU.java:295)
        at apdu4j.CommandAPDU.<init>(CommandAPDU.java:85)
        at pro.javacard.gp.GPTool.main(GPTool.java:222)

What can I do about that? Tested on both J2E081 and J3D081.

Thanks!

**Comment by darconeous** [comment]
That APDU has an invalid length field, it is never making it to the card.

**Comment by CueMaxX** [comment]
So.. is the wiki page wrong then?

**Comment by darconeous** [comment]
Breaking down the APDU:

```
0024039B 22 30208018101112131415161718191A1B1C1D1E1F2021222324252627
```

We have a specified payload length of 0x22 bytes, but the payload has only 0x1c bytes. So, yes, the wiki is wrong.

It is unclear to me if that is the only thing wrong or not. If that is the only thing that was wrong, then this would be the correct APDU:

```
0024039B 1C 30208018101112131415161718191A1B1C1D1E1F2021222324252627
```

**Comment by dengert** [comment]
And the 3020 should be 301A

**Comment by darconeous** [comment]
I'm guessing that it was just a copy-paste error: the last four bytes of the APDU are missing. I think those are just key bytes.

**Comment by CueMaxX** [comment]
Thanks so far!
Does that mean I have to add those last six bytes at the end of the APDU? How do I determine which bytes to send there?

**Comment by dengert** [comment]
Example looks like adding a default triple-DES key that is 3 des keys, i.e. 24 decimal bytes.  
the 8018 is tag and length. 
1011121314151617  18191A1B1C1D1E1F  2021222324252627

the 8018 is tag and length.

**Comment by makinako** [comment]
Hi guys, Yep the security wiki is wrong. Copy/paste for sure.
I've updated the ASN.1 example at the top, which had an incorrect APDU and DER-TLV object length and also the object length for the 2 symmetric keys in the test apdu script at the bottom of that page.
I believe this also links to issue #10 where the length is not being properly checked. In the next few weeks I'm going to be running through this and all the other issues in a wayyyy overdue update so I'll put up a new full set of test scripts.
Thanks!
