### ISSUE TITLE
Consider limited keys to one-per-id (no multiple mechanisms instantiated)

### ISSUE THREAD

**Issue by makinako** [makinako/OpenFIPS201#24]
At present, in pre-perso you can define a key multiple times with different mechanisms. This is great because you may have a need to choose at perso which one you want, however there doesn't seem to be a point in allowing you to actually generate/inject multiple instances of one ID.

This is especially true of PKI keys because for each key you must have a corresponding certificate of which there can only be one data object, so having more than one mechanism instantiated is useless imho. I'm thinking of putting a restriction in that lets you pre-perso/define all the mechanisms you want to support, but only can be initialised.

The only downside I can see is with symmetric, where there doesn't need to be a corresponding certificate. 
Options are:

1. Do nothing, allow it anyway
2. Implement it strictly, given the fact that you only have one certificate
3. Add it as a bake-in option (FEATURE_RESTRICT_SINGLE_KEY_INSTANCE)
4. Add it as a key role (Role.restrictSingle) option per-key

**Comment by dmercer-google** [comment]
About the only real world reason I can think of to support multiple keys per slot is to make broad testing in the NIST PIV Test Runner possible.  It uses certs hard coded in its config to verify signatures.  In card usages outside of a test environment I cant see the need for multiple keys per slot being necessary.  That said, "[There are strange things done in the midnight sun](https://www.poetryfoundation.org/poems/45081/the-cremation-of-sam-mcgee)" of legacy PIV implementations so I think adding a feature flag that defaults to restricting to a single instance is a good idea.

**Comment by makinako** [comment]
The outcome of this is it will be a configuration flag, which defaults to true as suggested by @dmercer-google. Since the intention is now to make use of run-time dynamic configuration (See #37), this won't require re-compiling the applet, just a script.

**Comment by makinako** [comment]
Closing as this is in the [v1.10.x releases](https://github.com/makinako/OpenFIPS201/releases/tag/v1.10.2) with the [Options.restrictSingleKey](https://openfips201.atlassian.net/wiki/spaces/OD/pages/622661/Applet+Pre-Personalisation#4.1-Applet-Options) configuration option.
