### ISSUE TITLE
RSA Signing with GENERAL AUTHENTICATE fails on JCOP 3 P60 cards 

### ISSUE THREAD

**Issue by CogitoGroupDevTeam** [makinako/OpenFIPS201#34]
### Problem Description
Signing data with an RSA key on the latest OpenFIPS201 applet causes the card to stall out, with the command eventually failing. Signing data with an ECC key works fine. This was tested on a JCOP 3 P60 CS with 144KB EEPROM.

This is what we're getting back from the card from the signing command:
```
A>> T=1 (4+0255) 1087079A FF 7C8201068200818201000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF003031300D060960864801650304020105000420450BFD34051D6CC04A80B36F3497C7849DD9A1F11A
A<< (0000+2) (49ms) 9000
A>> T=1 (4+0011) 0087079A 0B B83CCB10DBECBC03548729 00
<< SCardTransmit got response 0x45d (null: null)
Failed to communicate with card in apdu4j.LoggingCardTerminal@244038d0: SCardTransmit got response 0x45d (null: null)
```
After some investigation, we've been able to get signing working again by not removing the public key from the card after keygen, though we're unable to determine exactly why this would affect later signing operations with the private key.
```
--- a/src/com/makina/security/OpenFIPS201/PIVKeyObjectPKI.java
+++ b/src/com/makina/security/OpenFIPS201/PIVKeyObjectPKI.java
@@ -100,8 +100,6 @@ public abstract class PIVKeyObjectPKI extends PIVKeyObject {
       // We effectively new'd these objects so we will make sure the memory
       // is freed up.
       keyPair = null;
-      // Any existing public key is now invalid
-      clearPublic();
       runGc();
     }
     return length;
```

### Steps to reproduce
Build and install the latest OpenFIPS201 applet onto a card. Run the example pre-personalisation script, and add an ECC P-256 and ECC P-384 key object for the 9A, 9C, 9D, and 9E keys. Then run the following commands with GlobalPlatformPro (or equivalent):
```
// Inject a test PIN
java -jar gp.jar -dv --reader "<reader>" --mode enc --sdaid A000000308000010000100 --secure-apdu 0424FF80083132333435363738

// Generate an RSA-2048 key in the 9A slot
java -jar gp.jar -dv --reader "<reader>" --mode enc --sdaid A000000308000010000100 --secure-apdu 0447009A05AC03800107

// Sign a padded hash using the 9A key, authenticating with the test PIN
java -jar gp.jar -dv --reader "<reader>" --applet A000000308000010000100 --apdu 00200080083132333435363738 --apdu 1087079AFF7C8201068200818201000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF003031300D060960864801650304020105000420450BFD34051D6CC04A80B36F3497C7849DD9A1F11A --apdu 0087079A0BB83CCB10DBECBC0354872900
```
The signing command will return the output from the log above.

**Comment by makinako** [comment]
Apologies I didn't receive a notification about this due to my Github settings. I haven't run the full PIV test runner suite on all my Javacard samples since the EC support has been introduced. I'll trial this against the P60's I have and merge. You probably saw a separate issue #22 regarding removing public keys. If there are implementation-specific problems where PKI primitives fall over if all parts aren't present, this does cause problems removing the public key portion.  I think it's better to be broadly compatible rather than a bit more efficient.

**Comment by makinako** [comment]
This PR has been accepted and merged, thanks for the patience!
