### ISSUE TITLE
OpenSC confuses OpenFIPS201's implementation of command chaining.

### ISSUE THREAD

**Issue by fishsoupisgood** [makinako/OpenFIPS201#4]
### Problem Description

Also in [OpenSC's issues as #1274] (https://github.com/OpenSC/OpenSC/issues/1274)

with current OpenSC master [1d4f59ea51dd1713a3b99186498cb8fe074abc4c](https://github.com/OpenSC/OpenSC/commit/1d4f59ea51dd1713a3b99186498cb8fe074abc4c) and current master of OpenFIPS201 [580bb5cd36c41c38d38eb86c985f05dbd38be0d5](https://github.com/makinako/OpenFIPS201/tree/580bb5cd36c41c38d38eb86c985f05dbd38be0d5) opensc is unable to read the certificates on the card

OpenSC send INS_PIV_GET_DATA to  read the certificate from the card

APDU: 00 CB 3F FF 05 5C 03 5F C1 05 08 

and the card responds with 

SW: 53 82 02 A4 70 82 02 9B 61 FF 

as card-piv.c is only probing for the length of the file at this point it doesn't want to read the whole
certificate, and as SC_APDU_FLAGS_NO_GET_RESP in apdu.flags is set, sc_transmit_apdu doesn't read the rest of the data.

the next apdu opensc sends attempts to read the certificate in full.

APDU: 00 CB 3F FF 05 5C 03 5F C1 02 08 

but the card is still waiting for opensc to complete reading the previous INS_PIV_GET_DATA and so responds with

SW: 68 83  (SW_LAST_COMMAND_EXPECTED)

OpenSC then assumes the slot is empty as it failed to read the cert

with the attached patch opensc completes the first read in full

APDU: 00 CB 3F FF 05 5C 03 5F C1 05 08 
SW: 53 82 02 A4 70 82 02 9B 61 FF 
APDU: 00 C0 00 00 FF 
SW: 30 ... 61 FF 
APDU: 00 C0 00 00 FF 
SW: 5B ... 61 A2 
APDU: 00 C0 00 00 FF 
SW: 4A ... 90 00 

and the subsequent read now succeeds.

APDU: 00 CB 3F FF 05 5C 03 5F C1 05 00 
SW: 53 ..  61 FF 
etc.

### Proposed Resolution

If this is a bug in OpenSC rather than an implementation error in OpenFIPS201 then the following patch fixes it. Although the solution is not optimal, as it causes lots of data to be read twice over the 
slow smartcard interface.

<pre>
--- opensc-0.17.1.orig/src/libopensc/apdu.c
+++ opensc-0.17.1/src/libopensc/apdu.c
@@ -424,7 +424,7 @@ sc_set_le_and_transmit(struct sc_card *c
 
 
 static int
-sc_get_response(struct sc_card *card, struct sc_apdu *apdu, size_t olen)
+sc_get_response(struct sc_card *card, struct sc_apdu *apdu, size_t olen, int complete_reads)
 {
 	struct sc_context *ctx  = card->ctx;
 	size_t le, minlen, buflen;
@@ -497,6 +497,11 @@ sc_get_response(struct sc_card *card, st
 			le = minlen;
 	} while (rv != 0 && minlen != 0);
 
+	while ( complete_reads && (rv > 0)) {
+		unsigned char resp[256];
+		size_t resp_len;
+		rv=card->ops->get_response(card, &resp_len, resp);
+	}
 	/* we've read all data, let's return 0x9000 */
 	apdu->resplen = buf - apdu->resp;
 	apdu->sw1 = 0x90;
@@ -512,7 +517,7 @@ sc_get_response(struct sc_card *card, st
  *  @return SC_SUCCESS on success and an error value otherwise
  */
 static int
-sc_transmit(sc_card_t *card, sc_apdu_t *apdu)
+sc_transmit(sc_card_t *card, sc_apdu_t *apdu, int complete_reads)
 {
 	struct sc_context *ctx  = card->ctx;
 	size_t       olen  = apdu->resplen;
@@ -536,8 +541,8 @@ sc_transmit(sc_card_t *card, sc_apdu_t *
 	 *    Unless the SC_APDU_FLAGS_NO_GET_RESP is set we try to read as
 	 *    much data as possible using GET RESPONSE.
 	 */
-	if (apdu->sw1 == 0x61 && (apdu->flags & SC_APDU_FLAGS_NO_GET_RESP) == 0)
-		r = sc_get_response(card, apdu, olen);
+	if (apdu->sw1 == 0x61 && (((apdu->flags & SC_APDU_FLAGS_NO_GET_RESP) == 0) || complete_reads))
+		r = sc_get_response(card, apdu, olen, complete_reads);
 	LOG_TEST_RET(ctx, r, "cannot get all data with 'GET RESPONSE'");
 
 	LOG_FUNC_RETURN(ctx, SC_SUCCESS);
@@ -609,7 +614,7 @@ int sc_transmit_apdu(sc_card_t *card, sc
 				break;
 			}
 
-			r = sc_transmit(card, &tapdu);
+			r = sc_transmit(card, &tapdu, 1);
 			if (r != SC_SUCCESS)
 				break;
 			if (last != 0) {
@@ -629,7 +634,7 @@ int sc_transmit_apdu(sc_card_t *card, sc
 		}
 	} else
 		/* transmit single APDU */
-		r = sc_transmit(card, apdu);
+		r = sc_transmit(card, apdu, 0);
 	/* all done => release lock */
 	if (sc_unlock(card) != SC_SUCCESS)
 		sc_log(card->ctx, "sc_unlock failed");
</pre>

[patch here](https://gist.github.com/fishsoupisgood/1c1b7a80ed8feb03d64ef1a57962ee76)

### Steps to reproduce

Build and install OpenFIPS201 on a smartcard (I had to s/RSAPrivateKey/RSAPrivateCRTKey/g s/ALG_RSA/ALG_RSA_CRT/g to get it to work on a J3A081 ), use the example script to populate the PIV objects. Inject a Key for 9B. Then use yubico-piv-tool to populate slot 9a with a key and selfsigned certitifcate. Finally run

<pre>
root@box:~# pkcs11-tool --type cert --list-objects
Using slot with index 2 (0x8)
</pre>

with the above patch

<pre>
root@box:~# pkcs11-tool --type cert --list-objects
Using slot with index 2 (0x8)
Certificate Object; type = X.509 cert
  label:      Certificate for PIV Authentication
  ID:         01
</pre>

### Logs

```
0x7f1a6ef58700 15:34:45.688 [opensc-pkcs11] pkcs15.c:2344:sc_pkcs15_read_file: called
0x7f1a6ef58700 15:34:45.688 [opensc-pkcs11] pkcs15.c:2345:sc_pkcs15_read_file: path=0101cece, index=0, count=-1
[...]
0x7f1a6ef58700 15:34:45.688 [opensc-pkcs11] reader-pcsc.c:284:pcsc_transmit:
Outgoing APDU (11 bytes):
00 CB 3F FF 05 5C 03 5F C1 05 08 ..?..\._...
0x7f1a6ef58700 15:34:45.688 [opensc-pkcs11] reader-pcsc.c:212:pcsc_internal_transmit: called
0x7f1a6ef58700 15:34:45.708 [opensc-pkcs11] reader-pcsc.c:293:pcsc_transmit:
Incoming APDU (10 bytes):
53 82 02 A4 70 82 02 9B 61 FF S...p...a.
0x7f1a6ef58700 15:34:45.708 [opensc-pkcs11] apdu.c:390:sc_single_transmit: returning with: 0 (Success)
[...]
0x7f1a6ef58700 15:34:45.708 [opensc-pkcs11] reader-pcsc.c:284:pcsc_transmit:
Outgoing APDU (11 bytes):
00 CB 3F FF 05 5C 03 5F C1 05 00 ..?..\._...
0x7f1a6ef58700 15:34:45.708 [opensc-pkcs11] reader-pcsc.c:212:pcsc_internal_transmit: called
0x7f1a6ef58700 15:34:45.720 [opensc-pkcs11] reader-pcsc.c:293:pcsc_transmit:
Incoming APDU (2 bytes):
68 83 h.
0x7f1a6ef58700 15:34:45.720 [opensc-pkcs11] apdu.c:390:sc_single_transmit: returning with: 0 (Success)
```

[Full log in gist](https://gist.github.com/fishsoupisgood/2bec0d6b5c0a7fd9472c530fc1192b58)

**Comment by dengert** [comment]
May Jave is a little rusty, but it looks like this would cause the the current chained command to be reset and the new command executed. 

--- a/src/com/makina/security/OpenFIPS201/ChainBuffer.java
+++ b/src/com/makina/security/OpenFIPS201/ChainBuffer.java
@@ -374,7 +374,7 @@ public final class ChainBuffer {
             if (context[CONTEXT_APDU_CLAINS] != (short)((Util.getShort(buffer, ISO7816.OFFSET_CLA) & CLA_MASK)) ||
                     context[CONTEXT_APDU_P1P2] != Util.getShort(buffer, ISO7816.OFFSET_P1)) {
                 resetAbort();
-                ISOException.throwIt(ISO7816.SW_LAST_COMMAND_EXPECTED);
+                return; /* different command, return to execute it */
             }
         }
 
@@ -450,7 +450,7 @@ public final class ChainBuffer {
         // CASE 1 - If the remaining data is LESS THAN the total data, look for a GET RESPONSE command (clear if it isn't)
         if (apduBuffer[ISO7816.OFFSET_INS] != INS_GET_RESPONSE && context[CONTEXT_REMAINING] != context[CONTEXT_LENGTH] ) {
             reset();
-            ISOException.throwIt(ISO7816.SW_LAST_COMMAND_EXPECTED);
+            return; /* different command, return to execuite it */
         }
 
         //

**Comment by Jakuje** [comment]
Some years ago, I was fixing very similar issue in the [libcacard](https://gitlab.com/spice/libcacard/commit/ad59105), which was exposing very similar issues when I tried to use it with OpenSC driver.

This was again issue with the software implementation of the applet that we did not see if we tested against real CAC cards.

**Comment by makinako** [comment]
Thanks for the feedback guys! This is the first issue external to the dev team so it's great to see!

There isn't any specific guidance that I've been able to see in ISO 7816 regarding the handling of incomplete command chains. I chose to go down the path of being strict and this has so far passed tests with the various internal PIV middleware implementations we use as well as the PIV Test Runner (which I don't believe covers this edge case now that I look again). 

The use case for probing the length makes complete sense and there is nothing currently in PIV that satisfies this, so I would propose that @dengert your patch looks fine (it will have to be in a couple of other sections as well), however it should be a compile-time conditional feature so that implementations that wish to strictly enforce command chaining can still do so.

So for example FEATURE_USE_STRICT_COMMAND_CHAINING would be added to Config.java. If enabled it would retain the current functionality, but if disabled it would allow any unexpected command to reset the current chain and return as if there was no active chain.

Thoughts? If this sounds OK the next question will be what should be the default? We'll have to explore any possible exceptional scenarios that could occur by disabling this.

**Comment by fishsoupisgood** [comment]
I think you very much want the default to be that a command can be aborted mid stride, I have several   PIV tokens all of them allow starting a new command having read partial data and I think you'll find most stacks expect this [I've not checked windows but will today]. Further I think the standard is quite clear that it's required behaviour:

NIST references ISO 7816-4 for the command structure, and ISO 7816-4 says (emphasis mine):
5.1.3 status bytes:
[...]
Two interindustry values of SW1 are independent from any transmission protocol. 
If SW1 is set  to  '61', then the process is completed and before issuing any other command, a GET RESPONSE command **may** be issued with the same CLA and using SW2 (number of data bytes still available) as short Le field.

**Comment by dengert** [comment]
I would suggest that  the default for FEATURE_USE_STRICT_COMMAND_CHAINING would be off. Most (or all) other PIV implements allow starting a new command at this point. I don't believe there are  exceptional scenarios that could occur by disabling this.

**Comment by makinako** [comment]
Ok so given the feedback and especially @fishsoupisgood the 'may' wording of section 5.1.3 in ISO-7816-4, we're going to run this against the PIV implementations just out of interested, but it looks like the default definitely needs to be to permit it (in fact even the existence of the feature flag is questionable given that it may break 7816 to enable it). Will update shortly.

**Comment by makinako** [comment]
It should be noted that this feature defaults to 'false', allowing commands to change mid-chain.
