### ISSUE TITLE
issue on J3H145

### ISSUE THREAD

**Issue by rollinbe** [makinako/OpenFIPS201#46]
We are unable to build the PIV filesystem.

the command : java -jar gp.jar -d -v -sdaid A000000308000010000100 --mode enc -s "00 DB 3F 00 10 30 0E 8A 01 01 8B 03 5F C1 07 8C 01 7F 8D 01 00"

return 6982 error Code 

We use J3H145 NXP and HID Omnikey 3121 card reader.

GlobalPlatformPro v20.01.23-0-g5ad373b
Running on Linux 4.19.0-8-amd64 amd64, Java 1.8.0_292 by AdoptOpenJDK
# Detected readers from JNA2PCSC
[*] VMware Virtual USB CCID 00 00
SCardConnect("VMware Virtual USB CCID 00 00", T=*) -> T=1, 3BDC18FF8191FE1FC38073C821136605036351000250
SCardBeginTransaction("VMware Virtual USB CCID 00 00")
Reader: VMware Virtual USB CCID 00 00
ATR: 3BDC18FF8191FE1FC38073C821136605036351000250
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3BDC18FF8191FE1FC38073C821136605036351000250

[DEBUG] GPSession - (I)SD AID: A000000308000010000100
A>> T=1 (4+0011) 00A40400 0B A000000308000010000100 00
A<< (0146+2) (55ms) 61818F4F0BA00000030800001000010079074F05A000000308500B4F70656E464950533230315F5049687474703A2F2F6E766C707562732E6E6973742E676F762F6E697374707562732F5370656369616C5075626C69636174696F6E732F4E4953542E53502E3830302D37332D342E706466AC1E80010080010380010880010A80010C800106800107800111800114060100 9000
[TRACE] GPSession -  [61]
[TRACE] GPSession -      [4F] A000000308000010000100
[TRACE] GPSession -      [79]
[TRACE] GPSession -          [4F] A000000308
[TRACE] GPSession -      [50] 4F70656E46495053323031
[TRACE] GPSession -      [5F50] 687474703A2F2F6E766C707562732E6E6973742E676F762F6E697374707562732F5370656369616C5075626C69636174696F6E732F4E4953542E53502E3830302D37332D342E706466
[TRACE] GPSession -      [AC]
[TRACE] GPSession -          [80] 00
[TRACE] GPSession -          [80] 03
[TRACE] GPSession -          [80] 08
[TRACE] GPSession -          [80] 0A
[TRACE] GPSession -          [80] 0C
[TRACE] GPSession -          [80] 06
[TRACE] GPSession -          [80] 07
[TRACE] GPSession -          [80] 11
[TRACE] GPSession -          [80] 14
[TRACE] GPSession -          [06] 00
[WARN] GPSession - No FCI returned to SELECT
Warning: no keys given, using default test key 404142434445464748494A4B4C4D4E4F
[WARN] PlaintextKeys - Don't know how to calculate KCV, defaulting to SCP02
[WARN] PlaintextKeys - Don't know how to calculate KCV, defaulting to SCP02
[WARN] PlaintextKeys - Don't know how to calculate KCV, defaulting to SCP02
[INFO] GPSession - Using card master keys: ENC=404142434445464748494A4B4C4D4E4F (KCV: 8BAF47) MAC=404142434445464748494A4B4C4D4E4F (KCV: 8BAF47) DEK=404142434445464748494A4B4C4D4E4F (KCV: 8BAF47) for null
[TRACE] GPSession - Generated host challenge: 15B6CFB236DC6BF0
A>> T=1 (4+0008) 80500000 08 15B6CFB236DC6BF0 00
A<< (0029+2) (102ms) 00008048009485073469FF030053370E331AC20A14728760D7A5A90244 9000
[DEBUG] GPSession - Host challenge: 15B6CFB236DC6BF0
[DEBUG] GPSession - Card challenge: 53370E331AC20A14
[DEBUG] GPSession - Card reports SCP03 i=00 with key version 255 (0xFF)
[INFO] GPSession - Diversified card keys: ENC=404142434445464748494A4B4C4D4E4F (KCV: 504A77) MAC=404142434445464748494A4B4C4D4E4F (KCV: 504A77) DEK=404142434445464748494A4B4C4D4E4F (KCV: 504A77) for SCP03
[INFO] GPSession - Session keys: ENC=5BCDE70553517CCB0835F8CCA7F0BAE7 MAC=5F41361D3F2FC49EF97308D4898E9D35 RMAC=B70FCCD1452094D1FBE49E07B95FF6B4, card keys=ENC=404142434445464748494A4B4C4D4E4F (KCV: 504A77) MAC=404142434445464748494A4B4C4D4E4F (KCV: 504A77) DEK=404142434445464748494A4B4C4D4E4F (KCV: 504A77) for SCP03
[DEBUG] GPSession - Verified card cryptogram: 728760D7A5A90244
[DEBUG] GPSession - Calculated host cryptogram: 0A4044378F077A50
A>> T=1 (4+0016) 84820300 10 0A4044378F077A50CB4ED26FC2CB0139
A<< (0000+2) (165ms) 9000
A>> T=1 (4+0040) 04DB3F00 28 9D4F051F355F0956B99E4858E4ED4DCE4EAE78C5393DD4F1E41E1FCB8477AB11A9BB28F5D5854CB4
A<< (0000+2) (121ms) 6982
SCardEndTransaction("VMware Virtual USB CCID 00 00")
SCardDisconnect("VMware Virtual USB CCID 00 00", true) tx:97/rx:183

**Comment by makinako** [comment]
The applet requires that you enable C_ENC and C_MAC or it will return 6982 (Security Conditions Not Satisfied), so in gpp that maps to '--mode mac --mode enc'.
Also, the card seems to be reporting the SCP option as 00 instead of 10. I'll have to test on my own J3H145 in the next day or 2 to see if this is forcing the wrong mode but you might need to update the configuration registers.

**Comment by rollinbe** [comment]
I have solved my problem with use another computer and these syntax command :
 
ava -jar gp.jar -key 404142434445464748494A4B4C4D4E4F --connect A000000308000010000100 --mode enc -s "00DB3F0010300E8A01018B035FC1078C017F8D0100" -d -v

**Comment by makinako** [comment]
Good to hear! Thanks for getting in touch
