### ISSUE TITLE
PIN Sequence limit too short in Appendix - NIST Compliant Profile

### ISSUE THREAD

**Issue by Muzosh** [makinako/OpenFIPS201#54]
Hello,

by running the commands of [Appendix - NIST Compliant Profile](https://openfips201.atlassian.net/wiki/spaces/OD/pages/491612/Appendix+-+NIST+Compliant+Profile) on a clean installation, the PIN Sequence policy is firstly set to 4:
![image](https://user-images.githubusercontent.com/30979983/211584684-b5ed4dce-2db7-477e-933d-2eeb0d5d7069.png)

However, in the next step, the PIN is told to be set to 123456, which will fail with SW_WRONG_DATA, because the in-code variable `maxAscending` is calculated to 6:
![image](https://user-images.githubusercontent.com/30979983/211584979-fe07f9e4-77db-461f-af36-3906d7a974b4.png).

I know that you should respect the configuration when setting PIN, but the documentation suggests we could just run all commands one by one to comply with the NIST profile, which is now incorrect in the first two steps.

Suggested solution: raise the PIN Sequence limit to 7 in the first APDU (Configuration Steps) on the page [Appendix - NIST Compliant Profile](https://openfips201.atlassian.net/wiki/spaces/OD/pages/491612/Appendix+-+NIST+Compliant+Profile)???

**Comment by Muzosh** [comment]
I did not wanted to suggest setting the ruleSequence and ruleDistinct to 0 (off) at first, because I did not study the standard that much yet and wanted to stick to the secure by default principle ;)

Turning it off seems much more logical in this case (extended feature). Great resolution, thanks!

**Comment by Muzosh** [comment]
Yes you are correct, it is an extension defined by the P1=FF (by design). The issue was mainly about failing extended command in "step-by-step" APDU list, which will now be resolved internally.

**Comment by makinako** [comment]
> So that looks like an extension to NIST standards.

That is correct @dengert, this is the [CHANGE REFERENCE DATA ADMIN](https://openfips201.atlassian.net/wiki/spaces/OD/pages/491550/Applet+Commands#6.2-Command---CHANGE-REFERENCE-DATA-ADMIN) command. In the case of PIN/PUK it does not require the old value to be supplied as it is an administrative command under SCP w/ENC+MAC.

The NIST version of the command as you described also checks against PIN policy rules for the new value.

P.S. @Muzosh confluence is updated!
