### ISSUE TITLE
Problem with jcardsim loading the applet

### ISSUE THREAD

**Issue by xhanulik** [makinako/OpenFIPS201#58]
Hello, I'm trying to use OpenFIPS201 applet with jcardsim.
First, build the CAP file with `ant` as
```
JC_HOME=$PWD/OpenFIPS201/tools/sdk/jc310 ant -v all -f build/build.xml
```
then create jcardsim configuration file
```
com.licel.jcardsim.card.applet.0.AID=A00000030800001000
com.licel.jcardsim.card.applet.0.Class=com.makina.security.openfips201.OpenFIPS201
com.licel.jcardsim.card.ATR=3B80800101
com.licel.jcardsim.vsmartcard.host=localhost
com.licel.jcardsim.vsmartcard.port=35963
```
but starting the applet with command (assuming that jcardsim JAR is ok)
```
java -noverify -cp OpenFIPS201/build/bin:jcardsim/target/jcardsim-3.0.5-SNAPSHOT.jar com.licel.jcardsim.remote.VSmartCard jcardsim.cfg
```
ends with exception
```
Exception in thread "main" javacard.framework.SystemException
	at javacard.framework.SystemException.throwIt(Unknown Source)
	at com.licel.jcardsim.base.Simulator.loadApplet(Simulator.java:146)
	at com.licel.jcardsim.base.Simulator.<init>(Simulator.java:114)
	at com.licel.jcardsim.base.Simulator.<init>(Simulator.java:65)
	at com.licel.jcardsim.remote.VSmartCard.startThread(VSmartCard.java:87)
	at com.licel.jcardsim.remote.VSmartCard.<init>(VSmartCard.java:43)
	at com.licel.jcardsim.remote.VSmartCard.main(VSmartCard.java:83)
```

I'm not sure, whether this problem is related to building the CAP file or rather jcardsim - do you have any experience using OpenFIPS201 with jcardsim, or maybe any idea what might be wrong? [Here](https://github.com/xhanulik/OpenSC/blob/openfips/.github/test-openfips201.sh) is the whole used script, some insight would be very helpful.

**Comment by makinako** [comment]
Hi @xhanulik I'll link to the thread about this on [licel/jcardsim](https://github.com/licel/jcardsim/issues/205) here for tracking. 

If you download the [Javacos JCIDE](https://www.javacardos.com/tools) environment, they have PC/SC enabled simulators that include basic GP functionality, including SCP03 and support for contact vs contactless. It's actually quite good.

I have historically used JCIDE and commercial tools (G&D JLoad) for dev/test, but am now using the NXP JCOP tools with eclipse for full simulation capabilities. It's free but of course you need the NDA in place with NXP which makes it not so OSS friendly. 
JCardSim is also great but the commercial GP module causes similar issues. 

I hope one day do have all tests executing in a fully OSS environment as part of a CI pipeline, so the hunt for the perfect simulator might result in extending an existing one.

**Comment by xhanulik** [comment]
Thank you! I will definitely check JCIDE. However, the main intention was to run some tests in CI with the applet, so I guess I'm out of luck.

**Comment by makinako** [comment]
It's something I would also love to find an elegant and legally unencumbered solution for too, so I'll close this for now but we'll see who solves the problem first :)
