### ISSUE TITLE
PIN_ALWAYS - Does it match NIST 800-73?

### ISSUE THREAD

**Issue by dengert** [makinako/OpenFIPS201#6]
NIST 800-73-4 (and similar wording in older versions) "3.2.1 X.509 Certificate for Digital Signature" says:

"The PKI cryptographic function (see Table 4b) is protected with a “PIN Always” or “OCC Always” access rule. In other words, the PIN or OCC data must be submitted and verified every time immediately before a digital signature key operation."

All other PIV cards I have seen interprete "immediately before" to mean no other card commands between the "verify" and the "digital signature key operation". 

Reading the the code it appears that other commands can be done between the "verify" and the "digital signature key operation".  It appears it is set when the verify is done and reset when the  `cspPIV.checkAccessModeObject()` is called for keys and data. But this does not cover other card commands such as verify Lc=0, or SELECT AID. (And maybe others.)

Every other PIV card I have seen resets the PIV Always for any APDU to the card. I like your version, but it does not match other cards.

**Comment by makinako** [comment]
This was discussed a fair bit. SP800-73-4 talks about it but only briefly. It is further described in [NIST-IR-7863 - Cardholder Authentication for the
PIV Digital Signature Key](https://cryptome.org/2015/06/nist-ir-7863.pdf) which was probably released to clarify this and other issues around the 9C key (i.e. PIN caching).

In the end we went with the following wording from this document (In '1 Introduction'):
>Federal Information Processing Standard (FIPS) 201 defines the Personal Identity Verification
(PIV) Card and supporting process requirements. A private cryptographic key, the digital
signature key (DSK), is specified for digitally signing messages and data. The DSK is generated
on the card and is never exported; all operations with this private key are performed by the PIV
Card. **FIPS 201 requires authentication of the cardholder via “explicit user action” each time the DSK is used to perform a cryptographic operation.**

So in a sense we are already being more restrictive by including any command that requires an access control check (such as GET/PUT data), which could arguably be performed after a PIN verification.

In any case, we are fortunately meeting with members of the FIPS201/NIST team tomorrow, so may be able to get some clarification! Many implementations haven't changed this logic in a while and the above document only came out in 2015.

Will update shortly.

**Comment by dengert** [comment]
Clarification of this would be helpful. 
OpenSC tries to follow 7863 and supports PIN PAD readers, and will allow a user to use pin caching with
applications that do not support PKCS\#11 CKA_ALWAYS_AUTHENTICATE. One thing it does not do is set a time limit for the cached pin.  

There are many other PIV like applications out in the field, that are not NIST approved. They have been developed to take advantage of existing software such as Microsoft's PIV driver, vendors PKCS\#11 modules and OpenSC.  So far these card all support the "PIN Always" requirements.  These cards are intended for non government use and thus don't have to follow all the policies such as found in FIPS201 and 7863 which are imposed on the middleware. 

OpenSC tries to support both worlds as best it can. (It check for the presents of FASC-N with non 9999 values to identify government issues cards.)

Can you ask the FIPS201/NIST people about use of PIV with OpenSSH and especially the ssh agent. 
OpenSSH is used in both worlds,  government and non government. Normally the DSK would not be used for authentication, but there are some non government users that want to use the DSK with OpenSSH and ssh agent. **There may be government user too.** It would help OpenSC to know where they stood on OpenSSH usage and PIN caching. 

(If Tim Polk or David Cooper are there, say hello from me.)

**Comment by makinako** [comment]
<insert excessive pause here> Hi Doug/others, my sincere apologies for the lack of attention to this repo! I'm currently going through all outstanding issues to close them out by the end of this month.

I wasn't able to get the clarification I needed from NIST on this issue at the time. I'm inclined to update this to the logic as @dengert described it originally, since this is the most common interpretation. 
Unless there is anything further to add, I'll go down this path and close this shortly.

**Comment by dengert** [comment]
The term "Common interpertation" should be "common card inforced policies". Every NIST approved PIV card I have ever seen enforces on the card the the PIN Always policy by not allowing **any** other APDU command between the verify and the 0x87 general authenticate sign command. 

OpenSC goes to great lengths to make sure this does not happen. 

When I started writing the PIV driver  16 years ago, Firefox would do PKCS11 find objects command between the verify and the sign which would cause all objects (including some big ones, like fingerprint or facial image) to be read by GET DATA.  I convinced mozilla to at least only read certificates. OpenSC caches in memory all the certificates upon startup. Thus Firefox or other application could still query certificates without doing any card commands.

OpenSC will also also spot that a PKCS11 Context Specific Login command is being done.
The only reason a Context Specific Login is used for is to provide the PIN from the user just before a sign operation to address the “explicit user action” requirement. So OpenSC will get and hold the PCSC lock before the Verify and the Sign operation are in the same PCSC transaction, thus avoiding interference by other processes that may be trying to access the card.

Since there are "PIV like" cards that may have other applets on the card,  OpenSC will also check login status at the start of every transaction to avoid interference from other processes that may have reset the login state. Some of these cards also did not implement correctly  how to handle a SELECT AID for an applet that does not exist on the card, making this even more complicated.

The U.S. Government has cards with both a CAC applet and a PIV applet on the card. I do not have one of these for testing, but it appears they can share common keys and certificates between both. As far as I can tell, the PIV applet will enforce the PIN Always requirement, but the CAC will not.  See https://github.com/OpenSC/OpenSC/issues/1531#issuecomment-638790397
So the PIV applet is following the PIV standards and CAC is following CAC standards. 

PIV standard says nothing about a clock,  so cards do not have a way to set a timeout limit by the card.  

Some of these "PIV like" cards/tokens, have a way to turn on or off the the "PIN Always"  enforcement on the card. But the PIV standards require it.  So OpenSC could be modified to  to spot this on "PIV like" devices early before PKCS11 sees the CKA_ALWAYS_AUTHENTICATE attribute of a key. I have been promised a Yubico 5.3 to test if this can be implemented.
They also have a "touch" capability Which could address any “explicit user action” requirement. 

One of the main problems with these "PIV like" devices or software implementations is they  have their own extensions, and expect OpenSC to support them after the fact without little or no support for the OpenSC project. 

NIST PIV specifications really only define the "read only" PIV user interactions, and leave it up to card vendor on how to provision/initialize their devices. So don't look to OpenSC to provide utilities for provisioning your device/implementation.

**Comment by makinako** [comment]
Well as far as can be managed, OpenFIPS201 aims to be a reference implementation and so all the more reason to go with (as you say) the common card enforced policies. Looking on it with a bit of distance, the SP800-73-4 section 3.2.1 states "... In other words, the PIN or OCC data
must be submitted and verified every time immediately before a digital signature key operation ...".
This is a more clear statement than the one I quoted originally (from NIST-IR-7863).

Regarding initialisation and perso, I don't agree with the extent that NIST decided to avoid specifying key management, etc. It is what it is and the result is client/middleware tools such as OpenSC end up needing to re-implement support for again and again, even between versions of the same cards. I've seen high-license-cost commercial PIV perso systems fail to keep up with this, so I wouldn't expect it from OpenSC.

**Comment by dengert** [comment]
I believe NIST left card management up to vendors to give them a
competitive advantage to get multiple vendors. CAC at that time was a
single vendor and expensive. 16 years ago...

**Comment by dengert** [comment]
OpenSC can not keep up card management when vendors only give out that info via NDA. I have always stated the OpenSC piv-tool was for testing, and not for card management.
and the OpenSC driver was for using the card. Yubico has their own tools, and the tools source is available in github. 

In defense of NIST, 800-73 does provide just enough to allow for provisioning of test cards but only if a key pairs are generated on the card. They did not include a command to load a private key.  But it requires a 9B 3DES or AES key already be on the card, but does not provide a way to change that key. 

They do hint cards can be GP cards as they refer to the Global PIN could be good enough to allow access to PIV applet, and talk about other applets on the card, and how to handle login state if changed to other applet. So your implementation could stick to NIST 800-73 standards, if you set the 9B key when you load the applet on the card, or use GP to change the 9B key or other keys.  

The uninitialize PIV cards I have seen come from the vendor with default 9B key or one you have requested when you order a batch of cards.  Instructions say how to change it to unique value for each card. 

piv-tool -A  M:9B:03 or -A  A:9B:03  with env PIV_EXT_AUTH_KEY=<path to file with 3DES or AES key> (and change the 03 to 08, 0A or 0C for AES-128, AES-192 or AES-256.).
to authenticate to the card to enable PUT DATA and Generate Keypair commands. (The code is there but I don't have any PIV cards that use AES for 9B, and even if I do, I don't want to take the chance of locking up the card.)

An example of a really old batch of PIV cards, 15 years or so was using 2DES: 
```
 #  with the factory default key, or last 9B03 key
export PIV_EXT_AUTH_KEY=cards/$1.9B03.key 
piv-tool -A A:9B:01 -s "04:DB:3F:ff:1E:5C:02:9B:01:53:18: then 24 bytes of new 2DES where first 8 bytes match last 8 bytes"
 #Then write the new 9B key to the  cards/$1.9B03.key
```
Note command is a put data to 9B 01. i.e. 2DES 

Yubico uses: -s"00:ff:ff:ff:1b:03:9b:18 and 24 bytes of new 3DES"

**Comment by dengert** [comment]
If you are interested in implementing 800-73-4 Secure Messaging, see https://github.com/dengert/OpenSC/tree/PIV-4-extensions
It has all the basics, and was tested against demo card.

**Comment by makinako** [comment]
Hi @dengert, SM/VCI hasn't been on the radar for our internal use cases yet and so we haven't been able to allocate time to it. Having said that, I have a high interest in making this applet as complete as possible, which means SM/VCI/OCC and general ECC support all need too be represented.
Thanks for the link to your SM work, it will certainly make it easier to perform integration testing against a known good base.
