### ISSUE TITLE
Setting up secure channel for presonalization is harder than it needs to be

### ISSUE THREAD

**Issue by fishsoupisgood** [makinako/OpenFIPS201#7]
gpshell (and others) attempt to read parameters before setting up a secure channel by sending the following APDU

 APDU: 80 CA 00 66 00 
 SW: 66 [... 76 bytes ...] 02 90 00 

this works fine with the SecurityDomain Applet, but when the OPENFips201 applet is selected, gpshell gets 

APDU: 80 CA 00 66 00 
SW: 6E 00 

I worked around this by having gpshell cache those data and selecting the SecurityDomain first. What is the expected what to set up the SCP without these data. 

I'm also slightly confused about the security properties of the secure channel. With most RSA applets, knowing the key for the security domain only grants the ability to add and remove applets, but in OpenFIPS201, it would appear that the security domain key can be used to reset the admin key, the PIN and the PUK. Is that a deliberate design decision, as it makes loading other applets administered by other parties exceedingly complicated as the ISD key can't be shared.

**Comment by makinako** [comment]
This is a good point. Retrieving the SCP parameters should be permitted. Tagging this as a bug and will review a fix.

As I'm sure you're aware there are a number of deliberate omissions in the PIV specification regarding administrative functions. For our purposes, we needed a mechanism for the CMS/CAMS to perform personalisation functions such as key injection and setting a default PIN that aren't addressed in PIV as well as our pre-perso operations. We consider these to be functions of the applet issuance system and therefore the presumption of holding the GP keys is there.

GP provides a simple mechanism to solve the case you described using Supplementary Security Domains (SSDs). This allows the separation of roles between card issuer and application issuer for exactly this reason. Keep in mind also that once the PIV applet is issued, normal PIV administrative functions (PUT DATA, CHANGE REF) can be executed using either the 9B key or an SCP session.

Our view is that the 9B key is not a secure mechanism for administration and we don't recommend enabling it. 9B doesn't provide any channel protection post-authentication. It is trivial to perform man-in-the-middle attacks on PIV administrative functions if an attacker has access to the host system, the USB reader or the network in the case of online 9B authentications. 
A practical example is to swap a PC/SC reader out on a shared computer system with one that can intercept and manipulate APDU's once it detects a 9B authentication has been successfully processed.

Secure Messaging in SP800-73-4 may address this, but isn't mandated or even seemingly recommended for administrative functions.

**Comment by fishsoupisgood** [comment]
using SCP is a good idea (most commercial tokens use some form of it) but using it both for authentication and transport security seems not. SSDs don't seem particularly well supported 
in the cards and toolsets I've used.

I think the winning plan might be to 

1) consider a secure channel "authenticated" only if no key granting the admin role is initialized.
2) only permit authentication to admin role keys to succeed over a secure channel.

J.

PS: thanks for writing this - the code is a huge improvement over the previous OSS PIV applet.

**Comment by dengert** [comment]
Would a simple solution be to SELECT AID of the  SecurityDomain Applet, get the SCP parameters then SELECT AID of the PIV?
This is assuming it is only required when doing administrative tasks. 

There is a point to be made for a 9B key...
PIV does not define a random number function. But it does define a "Witness"  using GENERAL AUTHENTICATE "'80 00' Returns '80 TL <encrypted random>' (as per definition)"
i.e. `00 87 00 9B 02 80 00` (If it did the APDU correctly). will return 8 or maybe 24 bytes of "random" data based.  Some cads support this, some do not, as they may not have a 9B key. One card only supports the first call to get a witness, then fails an any other attempt.  

The comments about switching readers after an authenticate does bring up some issues. with this. 

OpenSC has used this if available for PKCS\#11 C_GenerateRandom See from 13 years ago:
http://opensc-devel.narkive.com/40yPK8lu/opensc-pkcs11-and-random-numbers

A quick look at the current OpenSC code, I don't see any use of OpenSSL involved in C_GenerateRandom. It could be added back in for the PIV at least 

Can you ask the FIPS201/NIST people what they think about Random Number Generation using the GENERAL AUTHENTICATE Witness?

**Comment by fishsoupisgood** [comment]
That's somewhat of a different question to weather or not the ISD key, soley, should be able to compromise the applet. But I would have expect some anti-hammering protection on Witness.

**Comment by ntwerdochlib** [comment]
Would someone be able to provide an example of using the pre personalisation scripts using gpshell and perhaps a standard JCO21 card?  I am currently using a gpshell script that starts with the following:

mode_211
enable_trace
enable_timer
establish_context
card_connect
select -AID a000000003000000
open_sc -security 3 -keyind 0 -keyver 0 -mac_key 404142434445464748494a4b4c4d4e4f -enc_key 404142434445464748494a4b4c4d4e4f // Open secure channel
select -AID A000000308000010
# ADD DATA OBJECT - 5FC107 - Card Capability Container
send_apdu -APDU 00DB3FFF0E300C8A01018B01078C017F8D0100

The issue I think is that having to select the OpenFIPS PIV Applet after creating the security channel causes the piv applet to not realize that a secure channel has been established.  Script response is: 6A80

Changing the script to send the APDU to select the PIV app using the secure channel:
#select -sc 1 -AID A000000308000010
send_apdu -sc 1 -APDU 00A4040008A000000308000010

Results in: 6E00

So if one wanted to use gpshell to handle the pre personalisation,  what exactly needs to be done?

**Comment by fishsoupisgood** [comment]
I don't think you can do this with gpshell out of the box, I had to patch debian's libglobalplatform (to which gpshell links) with this patch to get it to work:

https://gist.github.com/fishsoupisgood/52b1c9724a97ad8ded1c4cf770374266

then reauth the connexion after selecting the applet

I use the following for a  J3D081 (security domain has AID on these cards A000000151000000, and
I'm using a different AID to you to select the applet I can't remember if that's because we had to
change the openfips aid for $reasons)

mode_211
enable_trace
enable_timer
establish_context
card_connect
select -AID A000000151000000 
open_sc -security 3 -keyind 0 -keyver 0 -mac_key <ISD KEY> -enc_key <ISD_KEY>
select -AID A00000030800001000
open_sc -security 3 -keyind 0 -keyver 0 -mac_key <ISD KEY> -en_key <ISD_KEY>
send_apdu -sc 1 -APDU 00DB3F000E300C8A01018B01078C017F8D0100

etc...

**Comment by martinpaljak** [comment]
What are you trying to do? Why don’t you establish the secure channel directly to the applet? Have you tried GlobalPlatformPro (what is sometimes more sane than gpshell) ?

**Comment by kategray** [comment]
@martinpaljak I seem to be getting the same response with GlobalPlatform Pro.  As an example:

```
C:\Kate\JavaCard\PIV>gp -d -v --applet A000000308000010000100 --mode enc -s "00 DB 3F 00 14 30 12 8A 01 02 8B 01 95 8C 01 01 8D 01 00 8E 01 07 8F 01 04"

GlobalPlatformPro 18.09.14-0-gb439b52
Running on Windows 10 10.0 x86, Java 1.8.0_191 by Oracle Corporation
# Detected readers from JNA2PCSC
[*] Generic Smart Card Reader Interface 0
[ ] JAVACOS Virtual Contact Reader 0
[ ] JAVACOS Virtual Contactless Reader 1
SCardConnect("Generic Smart Card Reader Interface 0", T=*) -> T=1, 3BF81300008131FE45FF4A32413034300012
SCardBeginTransaction("Generic Smart Card Reader Interface 0")
Reader: Generic Smart Card Reader Interface 0
ATR: 3BF81300008131FE45FF4A32413034300012
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3BF81300008131FE45FF4A32413034300012

A>> T=1 (4+0000) 00A40400 00
A<< (0103+2) (60ms) 6F658408A000000003000000A5599F6501FF9F6E06479100783300734A06072A864886FC6B01600C060A2A864886FC6B02020101630906072A864886FC6B03640B06092A864886FC6B040215650B06092B8510864864020103660C060A2B060104012A026E0102 9000
[DEBUG] GlobalPlatform - Auto-detected ISD: A000000003000000
Warning: no keys given, using default test key 404142434445464748494A4B4C4D4E4F
A>> T=1 (4+0008) 80500000 08 2B82CBAD09EFB76F 00
A<< (0028+2) (70ms) 00008319019815991622FF0200FF368DEBD10E309FA5F5FAFB17830E 9000
[DEBUG] GlobalPlatform - Host challenge: 2B82CBAD09EFB76F
[DEBUG] GlobalPlatform - Card challenge: 00FF368DEBD10E30
[DEBUG] GlobalPlatform - Card reports SCP02 with key version 255 (0xFF)
[DEBUG] GlobalPlatform - Will do SCP02 (8)
[DEBUG] PlaintextKeys - Card keys: {DEK=type=RAW bytes=404142434445464748494A4B4C4D4E4F, MAC=type=RAW bytes=404142434445464748494A4B4C4D4E4F, ENC=type=RAW bytes=404142434445464748494A4B4C4D4E4F}
[DEBUG] GlobalPlatform - Verified card cryptogram: 9FA5F5FAFB17830E
[DEBUG] GlobalPlatform - Calculated host cryptogram: 55D0FD1FC3D5CD38
A>> T=1 (4+0016) 84820300 10 55D0FD1FC3D5CD384CC373F6962EEEFF
A<< (0000+2) (67ms) 9000
A>> T=1 (4+0032) 04DB3F00 20 79CB2E693720685B4D5B0B3517734A1750A95618EFD45DC525C971B38C2A57AE
A<< (0000+2) (32ms) 6E00
SCardEndTransaction(Generic Smart Card Reader Interface 0)
SCardDisconnect("Generic Smart Card Reader Interface 0", true)
```

If I'm reading it right, it looks like it's encrypted and still returning "6E 00".

**Comment by fishsoupisgood** [comment]
@martinpaljak - "If that is the case with some tools, it is a bug, sort of."  - yes I agree but sadly there are enough tools that expect that behaviour, and not all of them are open source, it's an easy fix which and it unbreaks using this excellent applet.

**Comment by makinako** [comment]
I'm a little unsure as to how to close this. Looking further into it, the card recognition data seems to be inherently out-of-scope and unknowable for the applet as the JC/GP api's don't provide all of this information. Instead, it seems like this is intended to belong to the ISD/SSD. I've also had a look around and can't find any examples of applets that implement SecureChannel and support getting card recognition data.

The purist in me says this isn't the applet's job so don't do it, but @fishsoupisgood made the valid point that if there are enough clients that do this, it would be a shame to exclude them.

@dmercer-google pointed out that you can work around it in GPShell by explicitly specifying the SCP options:
e.g. open_sc -keyind 0 -keyver 1 -enc_key <foo> -mac_key <bar> -sesurity [x] -scp [y] -scpimpl [z]

My question is, does anyone know of examples where this is implemented? If there isn't a precedent we can refer to I'm inclined to close this as a wontfix.

**Comment by dmercer-google** [comment]
All that you need prior to setting up a SCP session is the version of the SCP protocol and the key version.  In the case of OpenFIPS201 the applet uses the same keys as that of the security domain it is part of.  To use OpenFIPS201 with GPShell I just call `get_secure_channel_protocol_details` after selecting the SD and prior to selecting the applet and all works fine.

As far as I can tell in JC there is no way for an applet to get card data so setting up an SCP session with out some prior knowledge of the security domain configuration is not possible.  Even if one hard coded the card data in the Applet key versions can change which would render any hard coded data in the applet useless.

I think that addressing this is out of scope until such time as JC allows one to query card data.

**Comment by makinako** [comment]
I'm going to close this as a wontfix since the consensus seems to be that this is not in the scope of the applet and there are workable solutions using GPShell. We can re-open if new information comes up.

**Comment by dengert** [comment]
@makinako from https://github.com/makinako/OpenFIPS201/issues/7#issuecomment-369207168 you said: Secure Messaging in SP800-73-4 may address this, but isn't mandated or even seemingly recommended for administrative functions.". 

I would like to point out https://github.com/OpenSC/OpenSC/pull/2053 adds SM and VCI support to the OpenSC PIV client. It has been tested with IDEMIA ID-One PIV cards with pre issued data. The OpenSC piv-tool has not been modified to do any administrative functions over SM, but could be.
