### ISSUE TITLE
Recommendations for a Java card  for PIV OpenFIPS201 applet. 

### ISSUE THREAD

**Issue by dengert** [makinako/OpenFIPS201#8]
As an OpenSC developer, I would like add NIST 800-73-4 Secure Messaging to the OpenSC PIV driver and test it using your applet.  

Can you recommend any specific cards that meet your Hardware requirements? 
Are there any cards that support both Contact and Contactless?

Preferable readily available in US. Would this one work?
 https://www.amazon.com/J2A080-NXP-based-EEPROM-stripe/dp/B01M2BGJ3P

But it is not obvious which cards meet the requirements. Cost is not the primary issue. I would only be buying a few cards for testing.  

(I see 2 other OpenSC developers are watching this site too. Maybe they have recommendations for a java card. )

**Comment by martinpaljak** [comment]
Have you seen this:

https://github.com/martinpaljak/GlobalPlatformPro/tree/master/docs/JavaCardBuyersGuide ?

If you want from US, I would suggest one of these:

https://www.smartcardfocus.us/shop/ilp/id~687/j3d081-80k/p/index.shtml (JavaCard 3.0.1, fancy crypto requires proprietary API-s)

https://www.smartcardfocus.us/shop/ilp/id~805/smartcafe-expert-7-0-215k-crypto-usb-token-s/p/index.shtml - JavaCard 3.0.4 and probably better crypto support, as it is more recent (I have one but have not yet tested it fully)

Also have a look at https://github.com/crocs-muni/JCAlgTest

Do not buy 2.2.2 cards like the one you linked for general playing around - they are old.

**Comment by dengert** [comment]
Thanks for the response. 
The https://www.smartcardfocus.us/shop/ilp/id~805/smartcafe-expert-7-0-215k-crypto-usb-token-s/p/index.shtml looks like what  want to test the PIV applet with the SM.

(I also see that device, in card form, is used as an approved https://www.idmanagement.gov/1429-gd-mobile-security-smartcafe-expert-7-0/    with HID Global ActivID Applet v2.7.5. So should work with teh open source PIV applet. 

Does it come with the keys?

Do I need to ask them any questions?

It looks like all I need is your https://github.com/martinpaljak/GlobalPlatformPro and maybe Oracle's JAVA CARD SDK if I want to modify the applet.

**Comment by makinako** [comment]
Closing this issue as it is a clarification/question. One thing I'll note for the archives is that OpenFIPS201 does not currently support Secure Messaging or any ECC-based mechanisms. This is likely to change soon.

**Comment by dengert** [comment]
BTW, I am working on implementing the 800-74-4 Secure Messaging, using an approved NIST card with test data. It supports SM, but not the pairing code needed for VCI.
Key establishment and SM are working with PKCS11-tool. I am working on error handling, clean up  and certificate verification this week.

Note 800-74-4 says:
If a PIV Card Application implements the optional secure messaging protocol for **non-card-management operations**, it shall be implemented as specified in this section.
